# Install system dependencies and PHP extensions
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libmcrypt-dev \
    libonig-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    libpq-dev \
    postgresql-client \
    git \
    curl \
    libzip-dev && \
    docker-php-ext-configure gd --with-jpeg --with-freetype && \
    docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip pdo pdo_mysql pdo_pgsql && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy custom php.ini configuration
COPY php.ini /usr/local/etc/php/

# Copy project files
COPY . /var/www/html

# Set working directory and permissions
WORKDIR /var/www/html
RUN chown -R www-data:www-data /var/www/html/storage && \
    chmod -R 775 /var/www/html/storage && \
    chmod -R 775 /var/www/html/public

# Copy entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Set entrypoint script as the entrypoint for the container
ENTRYPOINT ["docker-entrypoint.sh"]

# Expose port 3030
EXPOSE 3030

# Command to start Laravel development server
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=3030", "--no-interaction"]
