version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-for-local
        image: local_realtime_chat_lenna_image
        container_name: local_realtime_chat_lenna_container
        restart: unless-stopped
        ports:
            - "8007:8007" # Sesuaikan dengan port yang digunakan oleh Laravel di Dockerfileeeeeeee CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000", "--no-interaction"]

        network_mode: "host"
        volumes:
            - ./:/var/www/html # Menyinkronkan seluruh direktori proyek Laravel dengan direktori /var/www/html di dalam kontainer

######################### JIKA TIDAK ADA STORAGE:LINK NYA MAKA JALANKAN CODE DIBAWAH DARI POIN (1-6) #####################
# 1. ls -l storage/app/public
# 2. sudo rm storage/app/public
# 3. sudo mkdir -p storage/app/public
# 4. sudo chmod -R 775 storage
# 5. docker compose -f docker-compose-for-local.yml exec web bash
# 6. php artisan storage:link
# docker compose -f docker-compose-for-local.yml up --build  -d
# docker compose -f docker-compose-for-local.yml exec web bash
# docker compose -f docker-compose-for-local.yml stop web
# docker compose -f docker-compose-for-local.yml rm web
# docker compose -f docker-compose-for-local.yml up --build -d web
# docker compose -f docker-compose-for-local.yml exec db mysql -u root -p